### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by countingtoten** [danielgtaylor/atom-api-blueprint-preview#18]
No view appears for the html, and there's this message in deprecations

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/jimw/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview.coffee:18:9)
```

**Comment by danielgtaylor** [comment]
I'll try to spend some time soon on the various deprecation and other warnings/issues from the Atom 1.0 changes.

**Comment by danielgtaylor** [comment]
This has been fixed with the latest release.
