### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by canyaman** [danielgtaylor/atom-api-blueprint-preview#20]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (~/.atom/packages/api-blueprint-preview/lib/api-blueprint-preview.coffee:18:9)
```

**Comment by canyaman** [comment]
https://atom.io/docs/latest/upgrading/upgrading-your-package

Package needs update. 

Replacing `atom.workspaceView.command` with `atom.commands.add 'atom-workspace',` only solves error message.

**Comment by danielgtaylor** [comment]
This has been fixed with the latest release.
