### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by madhon** [danielgtaylor/atom-api-blueprint-preview#28]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.
```
Object.Object.defineProperty.get (C:\Users\jdouglas\AppData\Local\atom\app-0.198.0\resources\app.asar\exports\atom.js:48:11)
Object.<anonymous> (C:\Users\jdouglas\.atom\packages\api-blueprint-preview\lib\api-blueprint-preview-view.coffee:2:1)
Object.<anonymous> (C:\Users\jdouglas\.atom\packages\api-blueprint-preview\lib\api-blueprint-preview-view.coffee:233:4)
Module._compile (module.js:452:26)
```

**Comment by danielgtaylor** [comment]
This has been fixed with the latest release.
