### ISSUE TITLE
Requires Aglio to be globally installed

### ISSUE THREAD

**Issue by jesperronn** [danielgtaylor/atom-api-blueprint-preview#5]
I have a project where Aglio is installed **locally**. Which makes the plugin fail since it looks for Aglio globally. Error on my machine:

```Previewing ApiBlueprint Failed

Command failed: /bin/sh -c aglio -i /tmp/atom.apib -t /Users/jesper/.atom/packages/api-blueprint-preview/templates/api-blueprint-preview.jade -o - /bin/sh: aglio: command not found
```

Can you change the plugin from
`/bin/sh -c aglio` 

to 

`$(npm bin)/aglio`

Since, I believe this to be more correct. Of course I am aware that this then requires aglio to be installed locally, but isn't this always the case? (package.json to specify)

Or, in your opinion, would it be better with a fallback?

**Comment by zdne** [comment]
same here, I am just curious are you guys using nvm?

**Comment by mansona** [comment]
Any update on this?

**Comment by danielgtaylor** [comment]
No updates on this yet. I suggest installing Aglio globally if you can, otherwise modify your `PATH` for the time being to point to the local installation. I'll try and figure out a good way to approach this.

**Comment by gaomd** [comment]
@zdne I'm using nvm and look like there is no solution currently.

**Comment by LinusU** [comment]
Can't we just add `aglio` as a dependency to this package and then just use the bundled version?

**Comment by danielgtaylor** [comment]
@LinusU last I had checked, `apm` was unable to install the module. This may have changed, however, since `protagonist` now uses `naan` and support Node.js 0.12. If it works then I'm not against bundling it.

**Comment by danielgtaylor** [comment]
As of the latest release it should try to pick up locally installed Aglio binary. Let me know if you run into any issues with this!

**Comment by jewelsjacobs** [comment]
Still doesn't work with nvm :(

**Comment by zdne** [comment]
> Fixed by installing aglio in the local project my blueprint files resided in

Uhm. I guess this is not optimal ...

**Comment by ttahmouch** [comment]
**Fails:**
```bash
# Open a new shell with `nvm` active in the current environment.
# Install `aglio` globally, and try `control+shift+a` in `atom` to no avail.
$ sudo npm install -g aglio
# Verify it is in an `nvm` directory.
$ npm config get prefix # ~/.nvm/v0.10.37
$ ls ~/.nvm/v0.10.37/bin/ # aglio
```
**Succeeds:**
```bash
# Open a new shell with `nvm` deactivated in the current environment.
$ nvm deactivate
# Install `aglio` globally, and try `control+shift+a` in `atom` ftw.
$ sudo npm install -g aglio
# Verify it is not in an `nvm` directory.
$ npm config get prefix # /usr/local
$ ls /usr/local/bin/ # aglio
```

I think this is a reasonable workaround because it only needs `nvm` deactivated long enough to install `aglio` to the default `npm` global, binary directory. `nvm` can be reactivated in subsequent shells. Though, this is not a true fix, I suppose.

**Comment by PatrixCR** [comment]
If you use NVM and installed Atom using the .deb package, try launching atom from the command line, instead of launching it from GUI launcher like Ubuntu's Unity.

If you use Ubuntu and still want to launch Atom from Unity, You can copy:

```
export NVM_DIR="/home/patrix/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
```

from `.bashrc` to `.profile` so you can launch Atom from the launcher (you may need to relogin so Ubuntu can read the changes to `.profile`).
