### ISSUE TITLE
Error in atom 1.9.9

### ISSUE THREAD

**Issue by lichenhao** [danielgtaylor/atom-api-blueprint-preview#64]
Previewing ApiBlueprint Failed

Command failed: aglio -i /tmp/atom.apib -t /Users/Ryota/.atom/packages/api-blueprint-preview/templates/api-blueprint-preview.jade -n /Users/Ryota/Documents/canvas-demo/src -o - /bin/sh: aglio: command not found

**Comment by BrydenR** [comment]
According to the README,
<quote>
"This plugin requires <a href=https://github.com/danielgtaylor/aglio>aglio</a> to be installed and in your path, via e.g:
<code>sudo npm install -g aglio</code>"
</quote>

**Comment by lichenhao** [comment]
aye, it fixed . Thank U
